INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (1, N'Barguna', N'Amtali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (2, N'Barguna', N'Bamna')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (3, N'Barguna', N'Barguna Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (4, N'Barguna', N'Betagi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (5, N'Barguna', N'Patharghata')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (6, N'Barguna', N'Taltali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (7, N'Barisal', N'Agailjhara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (8, N'Barisal', N'Babuganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (9, N'Barisal', N'Bakerganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (10, N'Barisal', N'Benari Para')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (11, N'Barisal', N'Gaurnadi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (12, N'Barisal', N'Hizla')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (13, N'Barisal', N'Barisal Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (14, N'Barisal', N'Mhendiganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (15, N'Barisal', N'Muladi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (16, N'Barisal', N'Wazirpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (17, N'Bhola', N'Bhola Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (18, N'Bhola', N'Burhanuddin')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (19, N'Bhola', N'Char Fasson')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (20, N'Bhola', N'Daulat Khan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (21, N'Bhola', N'Lalmohan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (22, N'Bhola', N'Manpura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (23, N'Bhola', N'Tazumuddin')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (24, N'Jhalokati', N'Jhalokati Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (25, N'Jhalokati', N'Kanthalia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (26, N'Jhalokati', N'Nalchity')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (27, N'Jhalokati', N'Rajapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (28, N'Patuakhali', N'Bauphal')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (29, N'Patuakhali', N'Dashmina')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (30, N'Patuakhali', N'Dumki')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (31, N'Patuakhali', N'Galachipa')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (32, N'Patuakhali', N'Kalapara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (33, N'Patuakhali', N'Mirzaganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (34, N'Patuakhali', N'Patuakhali Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (35, N'Patuakhali', N'Rangabali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (36, N'Pirojpur', N'Bhandaria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (37, N'Pirojpur', N'Kawkhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (38, N'Pirojpur', N'Mathbaria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (39, N'Pirojpur', N'Nazirpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (40, N'Pirojpur', N'Pirojpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (41, N'Pirojpur', N'Swarupkati')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (42, N'Pirojpur', N'Zianagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (43, N'Bandarban', N'Alikadam')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (44, N'Bandarban', N'Bandarban Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (45, N'Bandarban', N'Lama')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (46, N'Bandarban', N'Naikhongchhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (47, N'Bandarban', N'Rowangchhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (48, N'Bandarban', N'Ruma')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (49, N'Bandarban', N'Thanchi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (50, N'Brahmanbaria', N'Akhaura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (51, N'Brahmanbaria', N'Banchharampur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (52, N'Brahmanbaria', N'Bijoynagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (53, N'Brahmanbaria', N'Brahmanbaria Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (54, N'Brahmanbaria', N'Ashuganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (55, N'Brahmanbaria', N'Kasba')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (56, N'Brahmanbaria', N'Nabinagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (57, N'Brahmanbaria', N'Nasirnagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (58, N'Brahmanbaria', N'Sarail')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (59, N'Chandpur', N'Chandpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (60, N'Chandpur', N'Faridganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (61, N'Chandpur', N'Haim Char')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (62, N'Chandpur', N'Hajiganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (63, N'Chandpur', N'Kachua')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (64, N'Chandpur', N'Matlab Dakshin')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (65, N'Chandpur', N'Matlab Uttar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (66, N'Chandpur', N'Shahrasti')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (67, N'Chittagong', N'Anowara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (68, N'Chittagong', N'Bayejid Bostami')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (69, N'Chittagong', N'Banshkhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (70, N'Chittagong', N'Bakalia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (71, N'Chittagong', N'Boalkhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (72, N'Chittagong', N'Chandanaish')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (73, N'Chittagong', N'Chandgaon')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (74, N'Chittagong', N'Chittagong Port')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (75, N'Chittagong', N'Double Mooring')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (76, N'Chittagong', N'Fatikchhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (77, N'Chittagong', N'Halishahar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (78, N'Chittagong', N'Hathazari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (79, N'Chittagong', N'Kotwali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (80, N'Chittagong', N'Khulshi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (81, N'Chittagong', N'Lohagara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (82, N'Chittagong', N'Mirsharai')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (83, N'Chittagong', N'Pahartali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (84, N'Chittagong', N'Panchlaish')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (85, N'Chittagong', N'Patiya')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (86, N'Chittagong', N'Patenga')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (87, N'Chittagong', N'Rangunia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (88, N'Chittagong', N'Raozan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (89, N'Chittagong', N'Sandwip')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (90, N'Chittagong', N'Satkania')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (91, N'Chittagong', N'Sitakunda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (92, N'Comilla', N'Barura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (93, N'Comilla', N'Brahman Para')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (94, N'Comilla', N'Burichang')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (95, N'Comilla', N'Chandina')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (96, N'Comilla', N'Chauddagram')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (97, N'Comilla', N'Comilla Sadar Dakshin')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (98, N'Comilla', N'Daudkandi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (99, N'Comilla', N'Debidwar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (100, N'Comilla', N'Homna')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (101, N'Comilla', N'Comilla Adarsha Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (102, N'Comilla', N'Laksam')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (103, N'Comilla', N'Manoharganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (104, N'Comilla', N'Meghna')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (105, N'Comilla', N'Muradnagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (106, N'Comilla', N'Nangalkot')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (107, N'Comilla', N'Titas')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (108, N'Cox''s Bazar', N'Chakaria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (109, N'Cox''s Bazar', N'Cox''s Bazar Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (110, N'Cox''s Bazar', N'Kutubdia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (111, N'Cox''s Bazar', N'Maheshkhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (112, N'Cox''s Bazar', N'Pekua')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (113, N'Cox''s Bazar', N'Ramu')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (114, N'Cox''s Bazar', N'Teknaf')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (115, N'Cox''s Bazar', N'Ukhia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (116, N'Feni', N'Chhagalnaiya')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (117, N'Feni', N'Daganbhuiyan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (118, N'Feni', N'Feni Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (119, N'Feni', N'Fulgazi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (120, N'Feni', N'Parshuram')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (121, N'Feni', N'Sonagazi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (122, N'Khagrachhari', N'Dighinala')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (123, N'Khagrachhari', N'Khagrachhari Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (124, N'Khagrachhari', N'Lakshmichhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (125, N'Khagrachhari', N'Mahalchhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (126, N'Khagrachhari', N'Manikchhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (127, N'Khagrachhari', N'Matiranga')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (128, N'Khagrachhari', N'Panchhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (129, N'Khagrachhari', N'Ramgarh')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (130, N'Lakshmipur', N'Kamalnagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (131, N'Lakshmipur', N'Lakshmipur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (132, N'Lakshmipur', N'Roypur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (133, N'Lakshmipur', N'Ramganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (134, N'Lakshmipur', N'Ramgati')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (135, N'Noakhali', N'Begumganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (136, N'Noakhali', N'Chatkhil')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (137, N'Noakhali', N'Companiganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (138, N'Noakhali', N'Hatiya')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (139, N'Noakhali', N'Kabirhat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (140, N'Noakhali', N'Senbagh')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (141, N'Noakhali', N'Sonaimuri')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (142, N'Noakhali', N'Subarnachar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (143, N'Noakhali', N'Noakhali Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (144, N'Rangamati', N'Baghaichhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (145, N'Rangamati', N'Barkal Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (146, N'Rangamati', N'Betbunia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (147, N'Rangamati', N'Belai Chhari Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (148, N'Rangamati', N'Kaptai Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (149, N'Rangamati', N'Jurai Chhari Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (150, N'Rangamati', N'Langadu Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (151, N'Rangamati', N'Naniarchar Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (152, N'Rangamati', N'Rajasthali Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (153, N'Rangamati', N'Rangamati Sadar Up')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (154, N'Dhaka', N'Adabor')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (155, N'Dhaka', N'Badda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (156, N'Dhaka', N'Bangshal')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (157, N'Dhaka', N'Biman Bandar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (158, N'Dhaka', N'Banani')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (159, N'Dhaka', N'Cantonment')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (160, N'Dhaka', N'Chak Bazar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (161, N'Dhaka', N'Dakshinkhan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (162, N'Dhaka', N'Darus Salam')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (163, N'Dhaka', N'Demra')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (164, N'Dhaka', N'Dhamrai')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (165, N'Dhaka', N'Dhanmondi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (166, N'Dhaka', N'Dohar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (167, N'Dhaka', N'Bhasan Tek')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (168, N'Dhaka', N'Bhatara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (169, N'Dhaka', N'Gendaria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (170, N'Dhaka', N'Gulshan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (171, N'Dhaka', N'Hazaribagh')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (172, N'Dhaka', N'Jatrabari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (173, N'Dhaka', N'Kafrul')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (174, N'Dhaka', N'Kadamtali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (175, N'Dhaka', N'Kalabagan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (176, N'Dhaka', N'Kamrangir Char')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (177, N'Dhaka', N'Khilgaon')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (178, N'Dhaka', N'Khilkhet')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (179, N'Dhaka', N'Keraniganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (180, N'Dhaka', N'Kotwali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (181, N'Dhaka', N'Lalbagh')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (182, N'Dhaka', N'Mirpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (183, N'Dhaka', N'Mohammadpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (184, N'Dhaka', N'Motijheel')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (185, N'Dhaka', N'Mugda Para')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (186, N'Dhaka', N'Nawabganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (187, N'Dhaka', N'New Market')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (188, N'Dhaka', N'Pallabi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (189, N'Dhaka', N'Paltan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (190, N'Dhaka', N'Ramna')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (191, N'Dhaka', N'Rampura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (192, N'Dhaka', N'Sabujbagh')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (193, N'Dhaka', N'Rupnagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (194, N'Dhaka', N'Savar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (195, N'Dhaka', N'Shahjahanpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (196, N'Dhaka', N'Shah Ali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (197, N'Dhaka', N'Shahbagh')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (198, N'Dhaka', N'Shyampur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (199, N'Dhaka', N'Sher-e-bangla Nagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (200, N'Dhaka', N'Sutrapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (201, N'Dhaka', N'Tejgaon')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (202, N'Dhaka', N'Tejgaon Industrial Area')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (203, N'Dhaka', N'Turag')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (204, N'Dhaka', N'Uttara Paschim')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (205, N'Dhaka', N'Uttara Purba')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (206, N'Dhaka', N'Uttar Khan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (207, N'Dhaka', N'Wari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (208, N'Faridpur', N'Alfadanga')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (209, N'Faridpur', N'Bhanga')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (210, N'Faridpur', N'Boalmari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (211, N'Faridpur', N'Char Bhadrasan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (212, N'Faridpur', N'Faridpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (213, N'Faridpur', N'Madhukhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (214, N'Faridpur', N'Nagarkanda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (215, N'Faridpur', N'Sadarpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (216, N'Faridpur', N'Saltha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (217, N'Gazipur', N'Gazipur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (218, N'Gazipur', N'Kaliakair')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (219, N'Gazipur', N'Kaliganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (220, N'Gazipur', N'Kapasia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (221, N'Gazipur', N'Sreepur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (222, N'Gopalganj', N'Gopalganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (223, N'Gopalganj', N'Kashiani')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (224, N'Gopalganj', N'Kotalipara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (225, N'Gopalganj', N'Muksudpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (226, N'Gopalganj', N'Tungipara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (227, N'Jamalpur', N'Bakshiganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (228, N'Jamalpur', N'Dewanganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (229, N'Jamalpur', N'Islampur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (230, N'Jamalpur', N'Jamalpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (231, N'Jamalpur', N'Madarganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (232, N'Jamalpur', N'Melandaha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (233, N'Jamalpur', N'Sarishabari Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (234, N'Kishoregonj', N'Austagram')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (235, N'Kishoregonj', N'Bajitpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (236, N'Kishoregonj', N'Bhairab')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (237, N'Kishoregonj', N'Hossainpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (238, N'Kishoregonj', N'Itna')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (239, N'Kishoregonj', N'Karimganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (240, N'Kishoregonj', N'Katiadi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (241, N'Kishoregonj', N'Kishoregonj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (242, N'Kishoregonj', N'Kuliar Char')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (243, N'Kishoregonj', N'Mithamain')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (244, N'Kishoregonj', N'Nikli')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (245, N'Kishoregonj', N'Pakundia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (246, N'Kishoregonj', N'Tarail')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (247, N'Madaripur', N'Kalkini')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (248, N'Madaripur', N'Madaripur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (249, N'Madaripur', N'Rajoir')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (250, N'Madaripur', N'Shibchar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (251, N'Manikganj', N'Daulatpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (252, N'Manikganj', N'Ghior')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (253, N'Manikganj', N'Harirampur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (254, N'Manikganj', N'Manikganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (255, N'Manikganj', N'Saturia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (256, N'Manikganj', N'Shibalaya')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (257, N'Manikganj', N'Singair')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (258, N'Munshiganj', N'Gazaria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (259, N'Munshiganj', N'Lohajang')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (260, N'Munshiganj', N'Munshiganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (261, N'Munshiganj', N'Serajdikhan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (262, N'Munshiganj', N'Sreenagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (263, N'Munshiganj', N'Tongibari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (264, N'Mymensingh', N'Bhaluka')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (265, N'Mymensingh', N'Dhobaura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (266, N'Mymensingh', N'Fulbaria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (267, N'Mymensingh', N'Gaffargaon')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (268, N'Mymensingh', N'Gauripur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (269, N'Mymensingh', N'Haluaghat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (270, N'Mymensingh', N'Ishwarganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (271, N'Mymensingh', N'Mymensingh Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (272, N'Mymensingh', N'Muktagachha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (273, N'Mymensingh', N'Nandail')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (274, N'Mymensingh', N'Phulpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (275, N'Mymensingh', N'Trishal')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (276, N'Narayanganj', N'Araihazar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (277, N'Narayanganj', N'Sonargaon')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (278, N'Narayanganj', N'Bandar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (279, N'Narayanganj', N'Narayanganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (280, N'Narayanganj', N'Rupganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (281, N'Narsingdi', N'Belabo')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (282, N'Narsingdi', N'Manohardi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (283, N'Narsingdi', N'Narsingdi Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (284, N'Narsingdi', N'Palash')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (285, N'Narsingdi', N'Roypura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (286, N'Narsingdi', N'Shibpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (287, N'Netrakona', N'Atpara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (288, N'Netrakona', N'Barhatta')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (289, N'Netrakona', N'Durgapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (290, N'Netrakona', N'Khaliajuri')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (291, N'Netrakona', N'Kalmakanda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (292, N'Netrakona', N'Kendua')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (293, N'Netrakona', N'Madan')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (294, N'Netrakona', N'Mohanganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (295, N'Netrakona', N'Netrakona Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (296, N'Netrakona', N'Purbadhala')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (297, N'Rajbari', N'Baliakandi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (298, N'Rajbari', N'Goalanda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (299, N'Rajbari', N'Kalukhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (300, N'Rajbari', N'Pangsha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (301, N'Rajbari', N'Rajbari Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (302, N'Sariatpur', N'Bhedarganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (303, N'Sariatpur', N'Damudya')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (304, N'Sariatpur', N'Gosairhat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (305, N'Sariatpur', N'Naria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (306, N'Sariatpur', N'Sariatpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (307, N'Sariatpur', N'Zanjira')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (308, N'Sherpur', N'Jhenaigati')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (309, N'Sherpur', N'Nakla')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (310, N'Sherpur', N'Nalitabari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (311, N'Sherpur', N'Sherpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (312, N'Sherpur', N'Sreebardi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (313, N'Tangail', N'Basail')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (314, N'Tangail', N'Bhuapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (315, N'Tangail', N'Ghatail')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (316, N'Tangail', N'Gopalpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (317, N'Tangail', N'Kalihati')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (318, N'Tangail', N'Madhupur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (319, N'Tangail', N'Mirzapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (320, N'Tangail', N'Nagarpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (321, N'Tangail', N'Sakhipur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (322, N'Tangail', N'Tangail Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (323, N'Bagerhat', N'Bagerhat Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (324, N'Bagerhat', N'Chitalmari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (325, N'Bagerhat', N'Fakirhat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (326, N'Bagerhat', N'Kachua')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (327, N'Bagerhat', N'Mollahat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (328, N'Bagerhat', N'Mongla')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (329, N'Bagerhat', N'Morrelganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (330, N'Bagerhat', N'Rampal')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (331, N'Bagerhat', N'Sarankhola')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (332, N'Chuadanga', N'Alamdanga')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (333, N'Chuadanga', N'Chuadanga Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (334, N'Chuadanga', N'Damurhuda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (335, N'Chuadanga', N'Jiban Nagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (336, N'Jessore', N'Abhaynagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (337, N'Jessore', N'Bagher Para')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (338, N'Jessore', N'Chaugachha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (339, N'Jessore', N'Jhikargachha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (340, N'Jessore', N'Keshabpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (341, N'Jessore', N'Jessore Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (342, N'Jessore', N'Manirampur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (343, N'Jessore', N'Sharsha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (344, N'Jhenaidah', N'Harinakunda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (345, N'Jhenaidah', N'Jhenaidah Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (346, N'Jhenaidah', N'Kaliganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (347, N'Jhenaidah', N'Kotchandpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (348, N'Jhenaidah', N'Maheshpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (349, N'Jhenaidah', N'Shailkupa')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (350, N'Khulna', N'Batiaghata')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (351, N'Khulna', N'Dacope')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (352, N'Khulna', N'Daulatpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (353, N'Khulna', N'Dumuria')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (354, N'Khulna', N'Dighalia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (355, N'Khulna', N'Khalishpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (356, N'Khulna', N'Khan Jahan Ali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (357, N'Khulna', N'Khulna Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (358, N'Khulna', N'Koyra')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (359, N'Khulna', N'Paikgachha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (360, N'Khulna', N'Phultala')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (361, N'Khulna', N'Rupsa')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (362, N'Khulna', N'Sonadanga')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (363, N'Khulna', N'Terokhada')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (364, N'Kushtia', N'Bheramara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (365, N'Kushtia', N'Daulatpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (366, N'Kushtia', N'Khoksa')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (367, N'Kushtia', N'Kumarkhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (368, N'Kushtia', N'Kushtia Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (369, N'Kushtia', N'Mirpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (370, N'Magura', N'Magura Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (371, N'Magura', N'Mohammadpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (372, N'Magura', N'Shalikha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (373, N'Magura', N'Sreepur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (374, N'Meherpur', N'Gangni')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (375, N'Meherpur', N'Mujib Nagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (376, N'Meherpur', N'Meherpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (377, N'Narail', N'Kalia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (378, N'Narail', N'Lohagara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (379, N'Narail', N'Narail Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (380, N'Satkhira', N'Assasuni')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (381, N'Satkhira', N'Debhata')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (382, N'Satkhira', N'Kalaroa')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (383, N'Satkhira', N'Kaliganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (384, N'Satkhira', N'Satkhira Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (385, N'Satkhira', N'Shyamnagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (386, N'Satkhira', N'Tala')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (387, N'Bogra', N'Adamdighi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (388, N'Bogra', N'Bogra Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (389, N'Bogra', N'Dhunat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (390, N'Bogra', N'Dhupchanchia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (391, N'Bogra', N'Gabtali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (392, N'Bogra', N'Kahaloo')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (393, N'Bogra', N'Nandigram')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (394, N'Bogra', N'Sariakandi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (395, N'Bogra', N'Shajahanpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (396, N'Bogra', N'Sherpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (397, N'Bogra', N'Shibganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (398, N'Bogra', N'Sonatala')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (399, N'Joypurhat', N'Akkelpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (400, N'Joypurhat', N'Joypurhat Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (401, N'Joypurhat', N'Kalai')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (402, N'Joypurhat', N'Khetlal')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (403, N'Joypurhat', N'Panchbibi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (404, N'Naogaon', N'Atrai')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (405, N'Naogaon', N'Badalgachhi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (406, N'Naogaon', N'Dhamoirhat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (407, N'Naogaon', N'Manda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (408, N'Naogaon', N'Mahadebpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (409, N'Naogaon', N'Naogaon Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (410, N'Naogaon', N'Niamatpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (411, N'Naogaon', N'Patnitala')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (412, N'Naogaon', N'Porsha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (413, N'Naogaon', N'Raninagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (414, N'Naogaon', N'Sapahar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (415, N'Natore', N'Bagatipara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (416, N'Natore', N'Baraigram')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (417, N'Natore', N'Gurudaspur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (418, N'Natore', N'Lalpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (419, N'Natore', N'Natore Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (420, N'Natore', N'Singra')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (421, N'Chapai Nababganj', N'Bholahat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (422, N'Chapai Nababganj', N'Gomastapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (423, N'Chapai Nababganj', N'Nachole')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (424, N'Chapai Nababganj', N'Chapai Nababganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (425, N'Chapai Nababganj', N'Shibganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (426, N'Pabna', N'Atgharia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (427, N'Pabna', N'Bera')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (428, N'Pabna', N'Bhangura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (429, N'Pabna', N'Chatmohar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (430, N'Pabna', N'Faridpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (431, N'Pabna', N'Ishwardi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (432, N'Pabna', N'Pabna Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (433, N'Pabna', N'Santhia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (434, N'Pabna', N'Sujanagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (435, N'Rajshahi', N'Bagha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (436, N'Rajshahi', N'Baghmara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (437, N'Rajshahi', N'Boalia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (438, N'Rajshahi', N'Charghat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (439, N'Rajshahi', N'Durgapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (440, N'Rajshahi', N'Godagari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (441, N'Rajshahi', N'Matihar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (442, N'Rajshahi', N'Mohanpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (443, N'Rajshahi', N'Paba')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (444, N'Rajshahi', N'Puthia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (445, N'Rajshahi', N'Rajpara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (446, N'Rajshahi', N'Shah Makhdum')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (447, N'Rajshahi', N'Tanore')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (448, N'Sirajganj', N'Belkuchi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (449, N'Sirajganj', N'Chauhali')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (450, N'Sirajganj', N'Kamarkhanda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (451, N'Sirajganj', N'Kazipur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (452, N'Sirajganj', N'Royganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (453, N'Sirajganj', N'Shahjadpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (454, N'Sirajganj', N'Sirajganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (455, N'Sirajganj', N'Tarash')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (456, N'Sirajganj', N'Ullah Para')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (457, N'Dinajpur', N'Birampur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (458, N'Dinajpur', N'Birganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (459, N'Dinajpur', N'Biral')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (460, N'Dinajpur', N'Bochaganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (461, N'Dinajpur', N'Chirirbandar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (462, N'Dinajpur', N'Fulbari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (463, N'Dinajpur', N'Ghoraghat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (464, N'Dinajpur', N'Hakimpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (465, N'Dinajpur', N'Kaharole')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (466, N'Dinajpur', N'Khansama')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (467, N'Dinajpur', N'Dinajpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (468, N'Dinajpur', N'Nawabganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (469, N'Dinajpur', N'Parbatipur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (470, N'Gaibandha', N'Fulchhari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (471, N'Gaibandha', N'Gaibandha Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (472, N'Gaibandha', N'Gobindaganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (473, N'Gaibandha', N'Palashbari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (474, N'Gaibandha', N'Sadullapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (475, N'Gaibandha', N'Saghata')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (476, N'Gaibandha', N'Sundarganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (477, N'Kurigram', N'Bhurungamari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (478, N'Kurigram', N'Char Rajibpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (479, N'Kurigram', N'Chilmari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (480, N'Kurigram', N'Phulbari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (481, N'Kurigram', N'Kurigram Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (482, N'Kurigram', N'Nageshwari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (483, N'Kurigram', N'Rajarhat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (484, N'Kurigram', N'Raumari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (485, N'Kurigram', N'Ulipur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (486, N'Lalmonirhat', N'Aditmari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (487, N'Lalmonirhat', N'Hatibandha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (488, N'Lalmonirhat', N'Kaliganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (489, N'Lalmonirhat', N'Lalmonirhat Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (490, N'Lalmonirhat', N'Patgram')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (491, N'Nilphamari Zila', N'Dimla Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (492, N'Nilphamari Zila', N'Domar Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (493, N'Nilphamari Zila', N'Jaldhaka Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (494, N'Nilphamari Zila', N'Kishoreganj Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (495, N'Nilphamari Zila', N'Nilphamari Sadar Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (496, N'Nilphamari Zila', N'Saidpur Upazila')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (497, N'Panchagarh', N'Atwari')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (498, N'Panchagarh', N'Boda')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (499, N'Panchagarh', N'Debiganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (500, N'Panchagarh', N'Panchagarh Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (501, N'Panchagarh', N'Tentulia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (502, N'Rangpur', N'Badarganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (503, N'Rangpur', N'Gangachara')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (504, N'Rangpur', N'Kaunia')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (505, N'Rangpur', N'Rangpur Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (506, N'Rangpur', N'Mitha Pukur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (507, N'Rangpur', N'Pirgachha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (508, N'Rangpur', N'Pirganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (509, N'Rangpur', N'Taraganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (510, N'Thakurgaon', N'Baliadangi')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (511, N'Thakurgaon', N'Haripur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (512, N'Thakurgaon', N'Pirganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (513, N'Thakurgaon', N'Ranisankail')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (514, N'Thakurgaon', N'Thakurgaon Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (515, N'Habiganj', N'Ajmiriganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (516, N'Habiganj', N'Bahubal')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (517, N'Habiganj', N'Baniachong')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (518, N'Habiganj', N'Chunarughat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (519, N'Habiganj', N'Habiganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (520, N'Habiganj', N'Lakhai')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (521, N'Habiganj', N'Madhabpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (522, N'Habiganj', N'Nabiganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (523, N'Maulvibazar', N'Barlekha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (524, N'Maulvibazar', N'Juri')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (525, N'Maulvibazar', N'Kamalganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (526, N'Maulvibazar', N'Kulaura')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (527, N'Maulvibazar', N'Maulvibazar Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (528, N'Maulvibazar', N'Rajnagar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (529, N'Maulvibazar', N'Sreemangal')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (530, N'Sunamganj', N'Bishwambarpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (531, N'Sunamganj', N'Chhatak')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (532, N'Sunamganj', N'Dakshin Sunamganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (533, N'Sunamganj', N'Derai')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (534, N'Sunamganj', N'Dharampasha')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (535, N'Sunamganj', N'Dowarabazar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (536, N'Sunamganj', N'Jagannathpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (537, N'Sunamganj', N'Jamalganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (538, N'Sunamganj', N'Sulla')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (539, N'Sunamganj', N'Sunamganj Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (540, N'Sunamganj', N'Tahirpur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (541, N'Sylhet', N'Balaganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (542, N'Sylhet', N'Beani Bazar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (543, N'Sylhet', N'Bishwanath')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (544, N'Sylhet', N'Companiganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (545, N'Sylhet', N'Dakshin Surma')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (546, N'Sylhet', N'Fenchuganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (547, N'Sylhet', N'Golapganj')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (548, N'Sylhet', N'Gowainghat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (549, N'Sylhet', N'Jaintiapur')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (550, N'Sylhet', N'Kanaighat')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (551, N'Sylhet', N'Sylhet Sadar')
INSERT INTO [dbo].[ThanaModel] ([Id], [DistrictName], [ThanaName]) VALUES (552, N'Sylhet', N'Zakiganj')
