SET IDENTITY_INSERT [dbo].[Chat] ON
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10001, N'Hi', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10002, N'Hlw', 1007, NULL, NULL, 1001, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10003, N'Kmn Achen?', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10004, N'Valo', 1007, NULL, NULL, 1001, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10005, N'Apni?', 1007, NULL, NULL, 1001, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10006, N'Valo..ki koren?', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10007, N'Project er kaj kori', 1007, NULL, NULL, 1001, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10008, N'Hi', 1001, NULL, NULL, 1014, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10009, N'Hi', 1001, NULL, NULL, 1015, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10010, N'ohh', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10011, N'nice', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10012, N'ok', 1007, NULL, NULL, 1001, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10013, N'nice', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10014, N'hey', 1001, NULL, NULL, 1015, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10015, N'hey', 1001, NULL, NULL, 1015, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10016, N'ok', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10017, N'ok', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10018, N'hey', 1001, NULL, NULL, 1002, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10019, N'78', 1001, NULL, NULL, 1007, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10020, N'ok', 1007, NULL, NULL, 1001, NULL, NULL)
INSERT INTO [dbo].[Chat] ([Id], [Text], [UserId], [UserName], [UserPic], [OppoId], [OppoName], [OppoPic]) VALUES (10021, N'oooo', 1001, NULL, NULL, 1007, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Chat] OFF
