INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (1, N'Barisal')
INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (2, N'Chittagong')
INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (3, N'Dhaka')
INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (4, N'Khulna')
INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (5, N'Mymensingh')
INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (6, N'Rajshahi')
INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (7, N'Rangpur')
INSERT INTO [dbo].[DivisionModel] ([Id], [DivisionName]) VALUES (8, N'Sylhet')
